name: shorts_a7md
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0-149.3.beta

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  lottie: ^3.1.2
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.2
  cloud_firestore: ^5.4.4
  shimmer: ^3.0.0
  uuid: ^4.5.1
  image_picker: ^1.1.2
  flutter_svg: ^2.0.10+1
  http: ^1.2.2
  chewie: ^1.8.5
  video_player: ^2.9.2
  ffmpeg_kit_flutter: ^6.0.3
  path_provider: ^2.1.4
  intl: ^0.19.0
  flutter_cache_manager: ^3.4.1
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/animations/loading.json
    - assets/images/user.svg
    - assets/images/reely.svg
    - assets/images/dev.jpg
    
    
    

  fonts:
    - family: ios
      fonts:
        - asset: assets/fonts/1.TTF


