// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjgfGH_J1muLhrVN748eC_XQ_Aq0XyfHo',
    appId: '1:32398866498:web:dabffcab431d172d2015db',
    messagingSenderId: '32398866498',
    projectId: 'shorts-app-a7md',
    authDomain: 'shorts-app-a7md.firebaseapp.com',
    storageBucket: 'shorts-app-a7md.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6eWQWZ5EjW5xePK0SshCVORQyuCeiC30',
    appId: '1:32398866498:android:13f097a680f3651e2015db',
    messagingSenderId: '32398866498',
    projectId: 'shorts-app-a7md',
    storageBucket: 'shorts-app-a7md.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn_skCYW71DRkZyeyaRdhcCc2wXtBmq5s',
    appId: '1:32398866498:ios:c40b34fe486936e92015db',
    messagingSenderId: '32398866498',
    projectId: 'shorts-app-a7md',
    storageBucket: 'shorts-app-a7md.appspot.com',
    iosBundleId: 'com.example.shortsA7md',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn_skCYW71DRkZyeyaRdhcCc2wXtBmq5s',
    appId: '1:32398866498:ios:c40b34fe486936e92015db',
    messagingSenderId: '32398866498',
    projectId: 'shorts-app-a7md',
    storageBucket: 'shorts-app-a7md.appspot.com',
    iosBundleId: 'com.example.shortsA7md',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjgfGH_J1muLhrVN748eC_XQ_Aq0XyfHo',
    appId: '1:32398866498:web:54dd41cdf78ad0522015db',
    messagingSenderId: '32398866498',
    projectId: 'shorts-app-a7md',
    authDomain: 'shorts-app-a7md.firebaseapp.com',
    storageBucket: 'shorts-app-a7md.appspot.com',
  );
}
